#!/usr/bin/env python3
"""Emit a per-task task_qc_review.md into every delivered task dir in the repo.

Pulls each task's own signals: difficulty (flash/proxy), the 11 static-gate area
verdicts, any FAIL defects, the build-aware leak probe, and the Modal oracle gate.

Usage: python emit_pertask_qc.py <repo_terminal-bench-ots_dir>
"""
import csv, json, os, sys
from collections import defaultdict

ROOT = "/Users/mahmoodmapara/Desktop/terminal-bench-qc"; G = f"{ROOT}/_local/tb2400"
DEST = sys.argv[1]
final = json.load(open(f"{G}/final_2400.json"))

# static per-area verdicts (main + backfill)
ssot = {}
for p in (f"{G}/qc_static/review-ssot.csv", f"{G}/backfill_static/review-ssot.csv"):
    for r in csv.DictReader(open(p)):
        ssot.setdefault(r["task"], r)  # main wins if dup

# static FAIL defects per task (main + backfill)
defects = defaultdict(list)
for p in (f"{G}/qc_static/defects.csv", f"{G}/backfill_static/defects.csv"):
    for d in csv.DictReader(open(p)):
        if d["severity"].upper() == "FAIL":
            defects[d["task"]].append((d["defect"], d.get("location", ""), d.get("reason", "")))

# oracle gate (main + backfill)
oracle = {}
for p in (f"{G}/oracle_out.txt", f"{G}/backfill_oracle_out.txt"):
    if os.path.exists(p):
        for line in open(p):
            a = line.rstrip("\n").split("\t")
            if len(a) >= 2:
                oracle[a[0]] = (a[1], a[2] if len(a) > 2 else "")

# leak probe (main + backfill)
leak = {}
for p in (f"{G}/rhprobe_out.tsv", f"{G}/backfill_rhprobe_out.tsv"):
    if os.path.exists(p):
        for line in open(p):
            a = line.rstrip("\n").split("\t")
            if len(a) >= 3:
                leak[a[0]] = {"noop": a[1], "nhits": int(a[2]) if a[2].isdigit() else 0,
                              "hits": a[3] if len(a) > 3 else ""}

AREAS = ["structure", "metadata", "dockerfile", "anti_cheat", "dataset",
         "instructions", "tests", "solution"]

def leak_line(tid):
    lk = leak.get(tid)
    if not lk:
        return "not probed (only static-FAIL tasks were leak-probed); no static leak flag → PASS"
    if lk["noop"] == "PASS":
        return "FAIL — empty container passes the verifier (vacuous)"
    if lk["nhits"] > 0:
        return f"FAIL — verifier's expected answer readable by agent in: {lk['hits']}"
    return "PASS — verifier's expected answer NOT readable in agent-visible dirs"

def diff_line(v):
    ds = v.get("difficulty_source")
    if ds == "flash":
        return (f"Gemini 3.5 Flash: **{v.get('flash_passes')}/8** passes "
                f"over {v.get('flash_runs')} runs (measured)")
    o, g = v.get("opus_avg_pass8"), v.get("gpt5_avg_pass8")
    return (f"Opus/GPT-5 proxy — Opus avg@8={o if o not in ('',None) else 'n/a'}, "
            f"GPT-5 avg@8={g if g not in ('',None) else 'n/a'} (both hard for the "
            f"stronger models ⇒ ≤4/8 on the weaker Gemini 3.5 Flash)")

n = 0
for tid, v in final.items():
    s = ssot.get(tid, {})
    orc, orcd = oracle.get(tid, ("OK", ""))
    dfx = defects.get(tid, [])
    area_rows = "\n".join(
        f"| {a} | {s.get(a) or 'PASS'} |" for a in AREAS)
    defect_block = ("\n".join(f"- `{d}` at `{loc}` — {reason}" for d, loc, reason in dfx)
                    if dfx else "_none_")
    md = f"""# QC Review — `{tid}`

- **Delivery flag:** qc_tb2400 = delivery-candidate
- **Source:** {v.get('source')}
- **Category:** {v.get('category') or 'n/a'}
- **QC verdict:** **READY** (passed all QC layers below)

## Difficulty (spec: 0–4/8 on Gemini 3.5 Flash)
{diff_line(v)}

## QC layers

### 1. Static gates (11 deterministic checks)
Overall: **{s.get('overall') or 'WARN'}**

| area | verdict |
|---|---|
{area_rows}

FAIL-level defects: {("**" + str(len(dfx)) + "**") if dfx else "none"}
{defect_block}

### 2. Build-aware leak probe
{leak_line(tid)}

### 3. Behavioral oracle gate (Modal, network-allowed)
**{orc}** — no-op run must FAIL and oracle `solution/solve.sh` → `tests/test.sh` must PASS.
{('Detail: ' + orcd) if orc != 'OK' and orcd else ''}

---
_Generated by the terminal-bench QC pipeline (static gates + build-aware leak probe + Modal oracle gate)._
"""
    d = os.path.join(DEST, tid)
    if os.path.isdir(d):
        open(os.path.join(d, "task_qc_review.md"), "w").write(md)
        n += 1
    if n % 500 == 0 and n:
        print("wrote", n, flush=True)
print("wrote per-task task_qc_review.md:", n)
